name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py


###What This Workflow Does (Step-by-step)
#Matrix Build

#Runs the same job on Python 3.8 and 3.9 (parallel jobs)

#Steps Inside Each Job:

# Checkout code → Gets repo code

# Set up Python → Installs Python (3.8 or 3.9)

# Install dependencies → Upgrades pip and installs pytest

#Run tests → Runs addition.py test using pytest from src/ folder
